### ISSUE TITLE
Update Verification for Season 8 Runes

### ISSUE THREAD

**Issue by dscalzi** [ChampionMains/Pyrobot#7]
The old runes API is deprecated and the new runes will not get their own API. This makes it impossible to verify an account currently.

For now you can switch to profile icon verification, a system implemented by OriannaBot 
(see molenzwiebel/OriannaBot#2)

**Comment by MingweiSamuel** [comment]
👍 wip

**Comment by MingweiSamuel** [comment]
Updated, LMK if there are any issues
253557b63b6b93d63f2b08a3d3d8a6d4764bfe75
